#!/bin/sh
#
# Very basic wrapper for D-Bus Unagi interface.

set -e

help()
{
    echo "Usage: $0 [OPTIONS] DBUS_ACTION"
    echo
    echo "OPTIONS:"
    echo "  -h, --help           display this help and exit"
    echo
    echo "DBUS_ACTION:"
    echo "  exit                 exit program"
    echo "  plugin.expose.enter  enter Expose"
}

if test -z "$1"
then
    help
    exit 1
fi
`echo "$1" | egrep -q -- '^(-h|--help)'` && help && exit 0

DBUS_NAME=org.minidweeb.unagi
DBUS_OBJECT_PATH=/org/minidweeb/unagi

# Required to avoid race condition with KeyRelease event. For example, if
# 'Return' key is set to select a Window within Expose:
#
#  1. Type this command in a terminal
#  2. Press Return key.
#  3. If the KeyRelease X Event is received by Unagi *after* entering Expose
#     (issuing GrabKeyboard), then this will select the current Window and
#     exit Expose
sleep 0.2

dbus-send --session --type=method_call --print-reply --dest="$DBUS_NAME" \
    "${DBUS_OBJECT_PATH}" "${DBUS_NAME}.$1" > /dev/null
